# version: '3'
# services:
#   accounting:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: saudi_project
#     command: uvicorn apps.main:app --host 0.0.0.0 --port 80 --reload --reload-include *
#     ports:
#       - "8000:80"
    
#     volumes:
#       - ./apps:/code/apps

version: '3'
services:
  web:
    build: .
    container_name: admin_apps
    command: uvicorn apps.main:app --host 0.0.0.0 --port 7000 --reload
    # command: uvicorn apps.main:app --host 172.26.14.250 --port 7000 --reload
    ports:
      - "7000:7000"
    volumes:
      - .:/code
    environment:
      - PYTHONUNBUFFERED=1

